# Test met IMGOLF in kader NEN 3610 Linked Data

PREFIX rdf:       <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:      <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:       <http://www.w3.org/2002/07/owl#>
PREFIX xsd:       <http://www.w3.org/2001/XMLSchema#> 
PREFIX skos: 	<http://www.w3.org/2004/02/skos/core#>
PREFIX geo: 	   <http://www.opengis.net/ont/geosparql#>
PREFIX imgolf:    <http://data.gwsw.nl/1.4/imgolf/>
PREFIX :          <http://sparql.gwsw.nl/bim/KoninklijkeHaagseGenCC#>

SELECT ?naamParc ?Par ?Nummer ?naam ?type ?Vlak 

WHERE
{ 
   ?obj rdf:type imgolf:Parcoursdeel ; 
        sesame:directType ?type .
    
   FILTER (!(isBlank(?obj)))
   FILTER (!(isBlank(?type)))
    
   ?obj imgolf:hasAspect
   [    rdf:type imgolf:Vlak ;
        imgolf:hasValue ?Vlak ; ] .
  
   optional {?obj rdfs:label ?naam .
   }
   optional
   {   
      ?obj imgolf:isPartOf ?cps .
      ?cps rdfs:label ?naamParc .
      optional {
       	   ?cps imgolf:hasAspect 
           [
              rdf:type imgolf:Nummer ;
              imgolf:hasValue ?Nummer ;
           ] .
       	   ?cps imgolf:hasAspect 
           [
              rdf:type imgolf:Par ;
              imgolf:hasValue ?Par ;
           ] . }
   }
}
