
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX gwsw: <{{&version}}>

SELECT DISTINCT ?naam ?uri ?type ?Punt ?AansluitingId ?AfstandTotBeginpunt ?AfstandTotBovenzijdePut ?AfstandTotEindpunt ?Begindatum ?Eigenaar ?Einddatum ?Fabrikant ?Gegevensbeheerder ?LeidingId ?Leverancier ?MateriaalHulpstuk ?Omtreklocatie ?Rioleringsbeheerder ?TheoretischeLevensduur

WHERE
{
  {
    ?obj rdf:type gwsw:Inlaat .
  }

  FILTER (!(isBlank(?obj)))
  ?obj sesame:directType ?type .
  FILTER (!(isBlank(?type)))

  optional {
    ?obj gwsw:hasAspect ?ori .
    ?ori rdf:type gwsw:Punt .
    ?ori gwsw:hasValue ?Punt .
  }

  optional { ?obj rdfs:label ?naam . }

  optional {?obj gwsw:hasAspect [rdf:type gwsw:Begindatum; gwsw:hasValue ?Begindatum] .}
  optional {?obj gwsw:hasAspect [rdf:type gwsw:Einddatum; gwsw:hasValue ?Einddatum] .}

  optional {?obj gwsw:hasAspect [rdf:type gwsw:AfstandTotBeginpunt; gwsw:hasValue ?AfstandTotBeginpunt] .}
  optional {?obj gwsw:hasAspect [rdf:type gwsw:AfstandTotBovenzijdePut; gwsw:hasValue ?AfstandTotBovenzijdePut] .}
  optional {?obj gwsw:hasAspect [rdf:type gwsw:AfstandTotEindpunt; gwsw:hasValue ?AfstandTotEindpunt] .}
  optional {?obj gwsw:hasAspect [rdf:type gwsw:Omtreklocatie; gwsw:hasValue ?Omtreklocatie] .}

  optional {?obj gwsw:hasAspect [rdf:type gwsw:TheoretischeLevensduur; gwsw:hasValue ?TheoretischeLevensduur] .}

  optional {?obj gwsw:hasAspect [rdf:type gwsw:MateriaalHulpstuk; gwsw:hasReference ?MateriaalHulpstuk] .}


  optional {
    ?obj gwsw:isPartOf ?aansluiting .
    ?aansluiting rdf:type gwsw:Aansluiting .
    ?aansluiting rdfs:label ?AansluitingId .
  }

  optional {
    ?obj gwsw:isPartOf ?leiding .
    ?leiding rdf:type gwsw:Leiding .
    ?leiding rdfs:label ?LeidingId .
  }

  optional {?obj gwsw:isInputOf [rdf:type gwsw:Eigenaar; rdfs:label ?Eigenaar] .}
  optional {?obj gwsw:isInputOf [rdf:type gwsw:Gegevensbeheerder; rdfs:label ?Gegevensbeheerder] .}
  optional {?obj gwsw:isInputOf [rdf:type gwsw:Rioleringsbeheerder; rdfs:label ?Rioleringsbeheerder] .}
  optional {?obj gwsw:isOutputOf [rdf:type gwsw:Fabrikant; rdfs:label ?Fabrikant] .}
  optional {?obj gwsw:isOutputOf [rdf:type gwsw:Leverancier; rdfs:label ?Leverancier] .}

  BIND (?obj AS ?uri)
}