# Dataset: Compositie van afvalwater-systeem: stelsels indelen (20260114)
# Voor de zekerheid, als er geen gebieden met stelsels zijn gedefinieerd

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

PREFIX gwsw: <http://data.gwsw.nl/1.5/totaal/>
#PREFIX gwsw: <{{&version}}>

SELECT ?rec

where
{
  BIND ("Stelsels Alphen en Chaam" as ?labObj)
  #BIND ("Stelsels {{&repository}}" as ?labObj)
  BIND ("{{Afvalwatersysteem}}" as ?labTyp) # Label bij URI GemeentelijkGebied

  ?part rdf:type gwsw:Stelsel .
  ?part rdfs:label ?labPart .
  ?part sesame:directType ?typP .
  ?typP rdfs:label ?labP .
  FILTER (lang(?labP) = "nl") # de nl-versie is er altijd (20251101)
  BIND (CONCAT("{{", ?labP, "}}") AS ?labTypP)

  BIND (concat("Het object van type ", ?labTypP, " met de naam \"", ?labPart, "\" .02.is onderdeel van het object van type ", ?labTyp, " met de naam \"", ?labObj, "\".") as ?rec) # (20260116)
  #BIND (concat("Het object ", ?labTyp, " \"", ?labObj, "\" .02.heeft als onderdeel ", ?labTypP, " \"", ?labPart, "\".") as ?rec) # (20260116)
  #BIND (concat(?labTyp, " \"", ?labObj, "\" .02.heeft als onderdeel ", ?labTypP, " \"", ?labPart, "\".") as ?rec) # (20260116)
  #BIND (concat("Het objecttype ", ?labTyp, " met de naam \"", ?labObj, "\" .02.heeft als onderdeel het objecttype ", ?labTypP, " met de naam \"", ?labPart, "\".") as ?rec)
}
