# Datamodel;: Soorten Fysieke objecten in NL-vorm (zie ook Lijsten) (20251013)
# Distinct toegevoegd, anders dubbeling als SuperClass een multiparent heeft (bij Lijsten, 20150914)
# Alleen klasse + superklasse in de, dat is voldoende om de soortenboom te herleiden

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

PREFIX gwsw: <http://data.gwsw.nl/1.6/totaal/>
#PREFIX gwsw: <{{&version}}>

SELECT DISTINCT ?rec #?json

FROM <http://www.ontotext.com/explicit> # GrpahDB: gebruik alleen expliciete (not-inferred) binnen default Graph

where
{
  BIND (str(iri(gwsw:)) AS ?aft) # De datamodel-prefix

  ?Class1 rdf:type owl:Class .
  FILTER (CONTAINS(str(?Class1), ?aft))
  ?Class1 rdfs:label ?Class .
  FILTER (lang(?Class) = "nl") # de nl-versie is er altijd (20251101)
  
  ?Class1 rdfs:subClassOf ?Class2 .
  ?Class2 rdf:type owl:Class .
  FILTER (CONTAINS(str(?Class2), ?aft))
 	?Class2 rdfs:label ?SuperClass1 .
  FILTER (lang(?SuperClass1) = "nl") # de nl-versie is er altijd (20251101)

  BIND (IF (CONTAINS(str(?Class), " "), CONCAT("{{", ?Class, "}}"), ?Class) AS ?labCls)

  BIND (IF (CONTAINS(str(?SuperClass1), " "), CONCAT("{{", ?SuperClass1, "}}"), ?SuperClass1) AS ?labSup)


  #BIND (concat("Type \"", ?Class, "\" is een subtype van \"", ?SuperClass1, "\"." ) as ?rec)
  #BIND (concat("Type ", ?labCls, " is een subtype van ", ?labSup, "." ) as ?rec)
  BIND (concat("Een ", ?labCls, " is een soortnaam.\nEen ", ?labCls, " is een subtype van ", ?labSup, "." ) as ?rec)
  #BIND (concat("{\"id\": \"", ?SuperClass1, "\", \"type\": \"klasse\", \"subklasse\": \"" , ?Class, "\"}" ) as ?json)
}
