# Validatie: Overzicht violations - lijstvorm
# 20150818

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX vali: <http://data.gwsw.nl/vali#>

# groepeer/sorteer opmerkingen (20180302)

select ?TypeMelding ?type ?naam ?AspectObject ?Opmerking (COUNT (*) AS ?at)

where 
{
    ?s rdf:type vali:Violation .
    ?s rdfs:label ?TypeMelding .
    ?s vali:sTyp ?type .
	
    optional 
    {
		?s vali:sLab ?nam .
    }
	BIND (IF (BOUND(?nam), ?nam, "Onbekend") as ?naam)
	
    optional 
    {
        ?s vali:sAsp ?AspectObject . 
    }
    optional 
    {
        ?s rdfs:comment ?Opmerking . 
    }
}
GROUP BY ?TypeMelding ?type ?naam ?AspectObject ?Opmerking
ORDER BY ASC(?TypeMelding) ASC(?type) ASC(?naam) ASC(?AspectObject) ASC(?Opmerking)