PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX vali: <http://data.gwsw.nl/vali#>
PREFIX : <http://data.gwsw.nl/1.3.1/totaal/>

# Insert triples met meldingen
# Via SERVICE verwijzen naar de te controleren database
# Inserts in aparte meldingen-database
# ?typ = type validatie
# ?msg = algemeen commentaar
# ?sLab = het label van het primaire onderwerp
# ?sTyp = het type van het primaire onderwerp
# ?sAsp = het aspect bij het primaire onderwerp
# ?punt = geometrie van putten
# ?lijn = geometrie van leidingen

INSERT
{
    [ 
	  rdf:type vali:Violation ;
	  rdfs:label ?typ ;
      vali:sLab ?sLab ;
      vali:sTyp ?sTyp ;
      vali:sAsp ?sAsp ;
	  vali:punt ?punt ;
	  vali:lijn ?lijn ;
      rdfs:comment ?msg ;
    ]
}
where 
{ 
    # te valideren database:
    SERVICE <##endpoint> # endpoint wordt de te valideren database <http://localhost:7200/repositories/...>
	{ # voeg in: de specifieke query op de database
	  ##query
	}
}
