# GWSW/Geo-thema Waterschap: Overnamepunt (20230416)

# Filter op:
# * heeft geometrie gwsw:Punt
# * is (super)type gwsw:Overnamepunt

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

#PREFIX gwsw: <http://data.gwsw.nl/1.6/totaal/>
PREFIX gwsw: <{{&version}}>

SELECT ?Punt ?type ?invoer ?code ?naam
WHERE
{ 
  ?obj rdf:type gwsw:Overnamepunt .
  ?obj sesame:directType ?type .

  ?obj gwsw:hasAspect
  [ 
    rdf:type gwsw:Punt ;
    gwsw:hasValue ?Punt ;
  ] .
  optional {?obj gwsw:hasAspect 
  [
      rdf:type gwsw:Invoer ;
      gwsw:hasValue ?invoer ;
  ] .}
  optional { ?obj rdfs:label ?naam . }  
  optional { ?obj rdfs:comment ?code . }
}