# GWSW/Geo-thema Waterschap: Lozingspunt (20230416)

# Filter op:
# * heeft geometrie gwsw:Punt
# * is (super)type gwsw:Lozingspunt

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

#PREFIX gwsw: <http://data.gwsw.nl/1.6/totaal/>
PREFIX gwsw: <{{&version}}>

SELECT ?Punt ?uri_leiding ?type ?code ?naam
WHERE
{ 
  ?obj rdf:type gwsw:Lozingspunt .
  ?obj sesame:directType ?type .

  ?obj gwsw:hasAspect
  [ 
    rdf:type gwsw:Punt ;
    gwsw:hasValue ?Punt ;
  ] .
   optional { ?obj rdfs:label ?naam . } # niet meer verplicht (alleen geometrie moet kloppen) (20220518)   

   optional {?obj gwsw:hasConnection [ # verbonden met leiding ?
      rdf:type gwsw:Vertex ;
      gwsw:isPartOf  [
        rdf:type gwsw:Leidingorientatie;
        gwsw:isAspectOf ?uri_leiding ; 
      ] ;
   ] . }
   optional {?obj rdfs:comment ?code. }
}