# GWSW/Geo-thema Waterschap: Zuiveringseenheid (20230416)

# Filter op:
# * heeft geometrie gwsw:Buitengrens
# * is (super)type gwsw:Zuiveringsgebied

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

#PREFIX gwsw: <http://data.gwsw.nl/1.6/totaal/>
PREFIX gwsw: <{{&version}}>

SELECT ?Vlak ?RWZI ?Code ?naam

WHERE
{ 
  ?obj gwsw:hasAspect ?ori .
  ?ori rdf:type gwsw:TopologischElement .
  FILTER (!(isBlank(?obj)))
  ?obj rdf:type gwsw:Zuiveringsgebied .
  ?obj sesame:directType ?type .

  ?ori gwsw:hasAspect
  [ 
    rdf:type gwsw:Buitengrens ;
    gwsw:hasValue ?Vlak ;
  ] .
  optional { ?obj rdfs:label ?naam . } # niet meer verplicht (alleen geometrie moet kloppen) (20220518)   

  optional {?obj gwsw:hasPart [ # heeft als deel RWZI ?
      rdf:type gwsw:RWZI;
      rdfs:label ?RWZI ; 
  ] . }
  optional { ?obj gwsw:hasAspect [
    rdf:type gwsw:Code ;
    gwsw:hasValue ?Code ;
  ] . }
  optional {?obj rdfs:comment ?comment. }
}