# Hyd_Uitlaat.spq
# Tbv conversie naar GWSW.hydx (20170904)

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX : <http://data.gwsw.nl/1.3.1/totaal/>

SELECT ?bUri ?Punt

WHERE
{ 
    ?uri sesame:directType :UitlaatPunt .
	
	?uri :isAspectOf ?bUri .
	?uri :hasAspect [
		rdf:type :Punt ;
		:hasValue ?Punt ; ] .
}
