# Dataset: Compositie van fysieke objecten (20251013)

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

PREFIX gwsw: <http://data.gwsw.nl/1.6/totaal/>
#PREFIX gwsw: <{{&version}}>

SELECT ?rec

where
{
  ?obj rdf:type gwsw:FysiekObject .
  ?obj rdfs:label ?lab . # doe voorlopig alleen dingen met een naam

    { # subquery: verzamel de onderdelen (alleen die met een naam) in een string
    SELECT ?obj (GROUP_CONCAT(?rec ; separator = " [en] ") as ?recPart)
    WHERE
    {
      OPTIONAL {
        ?obj gwsw:hasPart ?part .
        ?part rdfs:label ?labP .
        BIND ("object" as ?grpPart) # hou het snel, waarschijnlijk voor AI niet essentieel
        BIND (concat(strafter(str(?part), "#"), "/", ?labP) as ?labPart)
        BIND (concat("het ", ?grpPart, " met identificatie \"", ?labPart, "\"") as ?rec)
      }
    }
    GROUP BY ?obj
  }
  BIND ("object" as ?grp) # hou het snel, waarschijnlijk voor AI niet essentieel
  BIND (concat(strafter(str(?obj), "#"), "/", ?lab) as ?labObj)
  BIND (concat("Het ", ?grp, " met identificatie \"", ?labObj, "\" heeft als onderdeel ", ?recPart) as ?rec)
}
