# Beheer_Leiding.rq (20170930-20200521)

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

#PREFIX : <http://data.gwsw.nl/1.5/totaal/>
PREFIX : <{{&version}}>

SELECT ?Stelsel ?stelseltype ?naam ?uri ?type ?Lijn ?beginpunt ?uriB ?eindpunt ?uriE ?Begindatum ?Einddatum ?BobBeginpuntLeiding ?datumInwinningBobBegin ?wijzeInwinningBobBegin ?BobEindpuntLeiding ?datumInwinningBobEind ?wijzeInwinningBobEind ?MateriaalLeiding ?VormLeiding ?BreedteLeiding ?HoogteLeiding ?LengteLeiding ?Wanddikte ?Verbindingstype ?Fundering ?datumLining ?DatumInspectie ?DatumReiniging ?WIONThema ?AantalWoningen ?Aantal_ieBedrijven ?Aantal_ieRecreatie ?AfvoerendOppervlak

WHERE
{ 
   ?lei rdf:type :Leiding .
   
   # Alles, behalve: (20190403)
   FILTER NOT EXISTS { ?lei rdf:type :Aansluitleiding . }
   FILTER NOT EXISTS { ?lei rdf:type :Goot . }

   ?lei sesame:directType ?type .
   FILTER (!(isBlank(?lei)))
   FILTER (!(isBlank(?type)))
    
   ?lei rdfs:label ?naam .

	optional {?lei :isPartOf 
	[ rdf:type :Stelsel ;
	rdfs:label ?Stelsel ;
	sesame:directType ?stelseltype ;
	] . }
	  
   ?lei :hasAspect ?ori .
   ?ori rdf:type :Leidingorientatie .

   ?ori :hasAspect # geometrie moet er zijn vanaf GWSW 1.4
   [ 
      rdf:type :Lijn ;
      :hasValue ?Lijn ;
   ] .

    optional # aansluiting begin. Hou synchroon: hyd_verbinding, mds_leiding
    {
        ?ori :hasPart ?bpnt .
        ?bpnt rdf:type :BeginpuntLeiding .
        ?bpnt :hasConnection ?bconn . # Let op: niet optioneel, anders loopt query slecht
		
        optional {
            ?bpnt :hasAspect ?bobB .
            ?bobB rdf:type :BobBeginpuntLeiding ;
                  :hasValue ?BobBeginpuntLeiding .

            optional {?bobB :hasAspect
            [
                rdf:type :Inwinning ;
                :hasAspect [
                rdf:type :DatumInwinning ;
                :hasValue ?datumInwinningBobBegin ;
                ] ;
            ] . }
            optional {?bobB :hasAspect
            [
                rdf:type :Inwinning ;
                :hasAspect [
                rdf:type :WijzeVanInwinning ;
                :hasReference ?wijzeInwinningBobBegin ;
                ] ;
            ] . }
        }
		
		# Hou het kort voor MDS (Delft liep vast op het vervolg)
        #?bconn :isAspectOf [ rdfs:label ?beginpunt; ] .

        ?bconn :isAspectOf ?_uriB . # lei in de query-resultaten voor zoekwerk (20200708)
        ?_uriB rdfs:label ?beginpunt .

        # uitgeschakeld, gebruik object-URI
        #optional # Stelselnaam erbij, voor unieke identificatie (20200706)
        #{
        #    ?bP :isPartOf* ?bS . # Doorzoeken naar stelseltype (ook vanuit compartimenten)
        #    ?bS rdf:type :Stelsel ;
        #        rdfs:label ?bStelsel .
        #}

		#optional {?bconn :hasAspect
		#[ 
		#	rdf:type :Punt ;
		#	:hasValue ?bgeo ;
		#] .	}
		## Bepaal naam van de aansluiting
		#
 		#{ ?bconn :isAspectOf ?bconn1 . }
        #union
        #{ ?bconn :isPartOf [ :isAspectOf ?bconn1 ; ] . } # rechtstreekse aansluiting op pomp
        #    
        #?bconn1 rdfs:label ?beginpunt1 .
		#
        #optional # toegevoegde naam?
		#{
		#	?bconn1 :isPartOf ?bconn2 . # deel van put / bouwwerk
        #    filter not exists {?bconn2 rdf:type :Stelsel .} # alles behalve Stelsel-types
		#	?bconn2 rdfs:label ?beginpunt2 .
		#}
        #bind (if(bound(?beginpunt1) && bound(?beginpunt2), concat(str(?beginpunt2), "/", str(?beginpunt1)), if (bound(?beginpunt1), ?beginpunt1, "")) as ?beginpunt)
	}
    optional # aansluiting eind. Hou synchroon: hyd_verbinding, mds_leiding
    {
		?ori :hasPart ?epnt .
		?epnt rdf:type :EindpuntLeiding .
      	?epnt :hasConnection ?econn . # Let op: niet optioneel, anders loopt query slecht

        optional {
            ?epnt :hasAspect ?bobE .
            ?bobE rdf:type :BobEindpuntLeiding ;
                  :hasValue ?BobEindpuntLeiding .
           
            optional {?bobE :hasAspect
            [
                rdf:type :Inwinning ;
                :hasAspect [
                rdf:type :DatumInwinning ;
                :hasValue ?datumInwinningBobEind ;
                ] ;
            ] . }
            optional {?bobE :hasAspect
            [
                rdf:type :Inwinning ;
                :hasAspect [
                rdf:type :WijzeVanInwinning ;
                :hasReference ?wijzeInwinningBobEind ;
                ] ;
            ] . }
        }
				
		# Hou het kort voor MDS (Delft liep vast op het vervolg)
        #?econn :isAspectOf [ rdfs:label ?eindpunt; ] .

        ?econn :isAspectOf ?_uriE . # lei in de query-resultaten voor zoekwerk (20200708)
        ?_uriE rdfs:label ?eindpunt .

        # uitgeschakeld, gebruik object-URI
        #optional # Stelselnaam erbij, voor unieke identificatie (20200706)
        #{
        #    ?eP :isPartOf* ?eS . # Doorzoeken naar stelseltype (ook vanuit compartimenten)
        #    ?eS rdf:type :Stelsel ;
        #        rdfs:label ?eStelsel .
        #}
        
		#optional {?econn :hasAspect
		#[ 
		#	rdf:type :Punt ;
		#	:hasValue ?egeo ;
		#] . }
		## Bepaal naam van de aansluiting
        #    
        #{ ?econn :isAspectOf ?econn1 . }
        #union
        #{ ?econn :isPartOf [ :isAspectOf ?econn1 ; ] . } # rechtstreekse aansluiting op pomp
        #    
      	#?econn1 rdfs:label ?eindpunt1 .
        #
        #optional # toegevoegde naam?
		#{
		#	?econn1 :isPartOf ?econn2 . # deel van put / bouwwerk
        #    filter not exists {?econn2 rdf:type :Stelsel .} # alles behalve Stelsel-types
		#	?econn2 rdfs:label ?eindpunt2 .
		#}
        #bind (if(bound(?eindpunt1) && bound(?eindpunt2), concat(str(?eindpunt2), "/", str(?eindpunt1)), if (bound(?eindpunt1), ?eindpunt1, "")) as ?eindpunt)
    }
   optional {?lei :hasAspect 
   [
       rdf:type :Begindatum ;
       :hasValue ?Begindatum ;
   ] .}
   optional {?lei :hasAspect 
   [
       rdf:type :MateriaalLeiding ;
       :hasReference ?MateriaalLeiding ;
   ] .}
   optional {?lei :hasAspect 
   [
       rdf:type :VormLeiding ;
       :hasReference ?VormLeiding ;
   ] .}
   optional {?lei :hasAspect 
   [
      rdf:type :DiameterLeiding ;
# Werkt niet altijd goed? Opgelost via COALESCE (20210521)
#      :hasValue ?BreedteLeiding ; # Diameter als breedte vermelden
       :hasValue ?dia ;  
   ] .}
   optional {?lei :hasAspect 
   [
      rdf:type :BreedteLeiding ;
      :hasValue ?br ;
   ] .}
   BIND (COALESCE (?br, ?dia) as ?BreedteLeiding) # de eerst geldende doet mee (20210521)
   
   optional {?lei :hasAspect 
   [
       rdf:type :HoogteLeiding ;
       :hasValue ?HoogteLeiding ;
   ] .}
   optional {?lei :hasAspect 
   [
       rdf:type :LengteLeiding ;
       :hasValue ?LengteLeiding ;
   ] .}
   optional {?lei :hasAspect 
   [
       rdf:type :Wanddikte ;
       :hasValue ?Wanddikte ;
   ] .}
   optional {?lei :hasAspect 
   [
       rdf:type :Verbindingstype ;
       :hasReference ?Verbindingstype ;
   ] .}
   optional {?lei :hasPart 
   [
       rdf:type :Fundering ;
       sesame:directType ?Fundering ;
   ] .}
   optional {?lei :hasPart 
   [
     rdf:type :Lining ;
     :hasAspect
     [
	  rdf:type :Begindatum ;
	  :hasValue ?datumLining ;
     ];
   ] .}
   optional {?lei :isInputOf 
   [
     rdf:type :Inspecteren ;
     :hasAspect
     [
	rdf:type :DatumMaatregel ;
	:hasValue ?DatumInspectie ;
     ];
   ] .}
   optional {?lei :isInputOf 
   [
     rdf:type :Reinigen ;
     :hasAspect
     [
	rdf:type :DatumMaatregel ;
	:hasValue ?DatumReiniging ;
     ];
   ] .}
   optional {?lei :hasAspect 
   [
       rdf:type :WIONThema ;
       :hasReference ?WIONThema ;
   ] .}
   optional {?lei :hasAspect 
   [
       rdf:type :AantalWoningen ;
       :hasValue ?AantalWoningen ;
   ] .}
   optional {?lei :hasAspect 
   [
       rdf:type :Aantal_ieBedrijven ;
       :hasValue ?Aantal_ieBedrijven ;
   ] .}
   optional {?lei :hasAspect 
   [
       rdf:type :Aantal_ieRecreatie ;
       :hasValue ?Aantal_ieRecreatie ;
   ] .}
   optional
   {
        SELECT ?lei (sum(?ao) as ?AfvoerendOppervlak) # sommeer de types ao
        WHERE
        {
           optional {?lei :hasAspect 
           [
               rdf:type :AfvoerendOppervlak ;
               :hasValue ?ao ;
           ] .}
        }
        GROUP BY ?lei
   }
    BIND (strafter(str(?lei), "#") AS ?uri)
    BIND (IF (BOUND(?_uriB), strafter(str(?_uriB), "#"), "") AS ?uriB)
    BIND (IF (BOUND(?_uriE), strafter(str(?_uriE), "#"), "") AS ?uriE)
}
