# Overzicht violations - sommatie per type melding en type object 
# 20160225

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX vali: <http://data.gwsw.nl/vali#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?TypeMelding ?TypeObject ?Opmerking (COUNT (*) AS ?Aantal)

WHERE
{ 
    ?vio sesame:directType vali:Violation . # het "bim-type", het niet-inferred type
    ?vio rdfs:label ?TypeMelding .
    ?vio vali:sTyp ?TypeObject .
    ?vio vali:sAsp ?Opmerking .
}
GROUP BY ?TypeMelding ?TypeObject ?Opmerking
ORDER BY ASC(?TypeMelding) ASC(?TypeObject) ASC(?Opmerking)
