# Validatie: Overzicht violations - sommatie per type melding
# 20150820

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX vali: <http://data.gwsw.nl/vali#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?TypeMelding ?Opmerking (COUNT (*) AS ?Aantal)

WHERE
{ 
    ?vio sesame:directType vali:Violation . # het "bim-type", het niet-inferred type
    ?vio rdfs:label ?TypeMelding .
    #?vio rdfs:comment ?Opmerking .
    ?vio vali:sAsp ?Opmerking .
}
GROUP BY ?TypeMelding ?Opmerking
ORDER BY ASC (?TypeMelding)
