# Mds_Reservoir.spq

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX : <http://data.gwsw.nl/1.3.1/totaal/>

SELECT DISTINCT ?Stelsel ?naam ?type ?Punt ?Begindatum

WHERE
{ 
   ?res rdf:type :Reservoir .
   
   ?res sesame:directType ?type .
    
   FILTER (!(isBlank(?res)))
   FILTER (!(isBlank(?type)))
    
   ?res rdfs:label ?naam .
   
   optional
   {   
      ?res :isPartOf 
      [ rdf:type :Stelsel ;
        rdfs:label ?Stelsel ;
      ] .
   }
   ?res :hasAspect ?ori ;
   
   { ?ori rdf:type :Bouwwerkorientatie . }
   UNION
   { ?ori rdf:type :Reservoirorientatie . } # Vanaf 1.3.3 niet meer geldig (reservoir wordt type bouwwerk)
   
   ?ori :hasAspect
       [ 
         rdf:type :Punt ; # Was Geometrie, wordt Punt (20200128)
         :hasValue ?Punt ;
       ] .

   optional {?res :hasAspect 
   [
       rdf:type :Begindatum ;
       :hasValue ?Begindatum ;
   ] .}
}
