PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX vali: <http://data.gwsw.nl/vali#>

# maak een lege validatie-output-database

CLEAR ALL;

INSERT DATA
{
    vali:Constraint rdf:type owl:Class .
    vali:sTyp rdf:type owl:AnnotationProperty .
    vali:sLab rdf:type owl:AnnotationProperty .
    vali:sAsp rdf:type owl:AnnotationProperty .
	vali:punt rdf:type owl:AnnotationProperty .
	vali:lijn rdf:type owl:AnnotationProperty .
}
