# Validatie: Overzicht violations - sommatie foute typeringen
# 20170308

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX vali: <http://data.gwsw.nl/vali#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sesame: <http://www.openrdf.org/schema/sesame#>

SELECT ?TypeMelding (COUNT (*) AS ?Aantal)

WHERE
{ 
    ?vio sesame:directType vali:Violation . # het niet-inferred type
    ?vio rdfs:label ?mld .
    bind ("[type = " as ?aft) # zoek op de marker (sync a) (20190831))
    filter (contains(str(?mld), ?aft))
    bind (strafter(str(?mld), ?aft) as ?TypeMelding)
}
GROUP BY ?TypeMelding
