# Test op niet-numeriek voor datatype min/max (20160222)
# Inference niet nodig, ontologie kan via service
# aangepast op separate CFK in primaire dataset (20190814)

where
{
	select distinct ?typ ?sTyp ?sLab ?sAsp ?msg ?punt ?lijn

	where 
	{ 
		# Zoek de dt_class met de restricties
		
		?dt1 xsd:maxInclusive ?val .
		?dt2 rdf:first ?dt1 .
		?dt3 rdf:rest ?dt2 .
		?dt4 owl:withRestrictions ?dt3 .
		?dt5 owl:equivalentClass ?dt4 .
		?dt5 rdfs:label ?sAsp .
		?dt6 owl:allValuesFrom ?dt5 .
		?dt7 rdfs:subClassOf ?dt6 .
		
		SERVICE <{{&endpoint}}> # endpoint wordt de te valideren dataset 
		{
			?asp rdf:type ?dt7 .
			?asp :hasValue ?Val .
			?s :hasAspect ?asp .

			# initialiseer ?msg

			FILTER (!(isNumeric(?Val)))
			
			BIND (CONCAT("Waarde [", str(?Val), "] niet numeriek") as ?msg)

			BIND ("{{&version}}" AS ?aft)

			# initialiseer ?sLab

			OPTIONAL # label hoeft er niet te zijn
			{
				?s rdfs:label ?s1 .
			}
			BIND ( IF(BOUND(?s1), ?s1, "") as ?sLab) # Wel initialiseren anders komen triples niet goed door in validatie-database

			# initialiseer ?sTyp

			?s sesame:directType ?t .
			FILTER (!(isBlank(?t)))
			BIND ( IF(contains(str(?t), ?aft), strafter(str(?t), ?aft), str(?t)) as ?sTyp)

			# initialiseer ?typ
			
			BIND ("Datatype niet correct" AS ?typ) # zelfde titel als check op xsd:datatype
				
			OPTIONAL
			{
			   ?s :hasAspect 
			   [
				  rdf:type :Putorientatie ;
				  :hasAspect
				  [ 
					rdf:type :Punt ;
					:hasValue ?punt ;
				  ]
			   ]
			}
			OPTIONAL
			{
			   ?s :hasAspect 
			   [
				  rdf:type :Leidingorientatie ;
				  :hasAspect
				  [ 
					rdf:type :Lijn ;
					:hasValue ?lijn ;
				  ]
			   ]
			}
		}
	}
}