PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

#PREFIX gwsw: <http://data.gwsw.nl/1.5/totaal/>
PREFIX gwsw: <{{&version}}>

SELECT ?Naam ?Type ?TypeNaam ?Geometrie

WHERE
{ 
   ?geb gwsw:hasAspect [
        rdf:type gwsw:TopologischElement ; # gebiedsoriëntatie, bouwwerkoriëntatie, ...
        gwsw:hasAspect [
        rdf:type gwsw:Buitengrens ;
        gwsw:hasValue ?Geometrie ; ] ] .
   FILTER (!(isBlank(?geb)))
  
   ?geb sesame:directType ?Type .
   FILTER (!(isBlank(?Type)))   

   ?geb rdfs:label ?Naam .
   ?Type rdfs:label ?TypeNaam . # De URI hoeft niet dekkend te zijn
   FILTER (lang(?TypeNaam) = "nl") # de nl-versie is er altijd (20251101)
}