PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

#PREFIX : <http://data.gwsw.nl/1.5/totaal/>
PREFIX : <{{&version}}>

SELECT ?Stelsel ?Naam ?Type ?TypeNaam ?Geometrie

WHERE
{ 
   ?lei :hasAspect [
		rdf:type :TopologischElement ; # lees lei-geo (vanaf versie 1.4 altijd aanwezig)
		:hasAspect
		[ 
			rdf:type :Lijn ;
			:hasValue ?Geometrie ;
		] 
   ] .
   FILTER (!(isBlank(?lei)))
   
   ?lei sesame:directType ?Type .
   FILTER (!(isBlank(?Type)))
   
   ?lei rdfs:label ?Naam .    
   ?Type rdfs:label ?TypeNaam . # De URI hoeft niet dekkend te zijn
   FILTER (lang(?TypeNaam) = "nl") # de nl-versie is er altijd (20251101)
    
    optional
    {
      ?lei :isPartOf 
      [ rdf:type :Stelsel ;
        rdfs:label ?Stelsel ;
      ] .
    }
}
