# Kentallen_Afvoernetwerk (20220511) (20220221) (20220202)
# Toon de gebieden (vlakken) die als deel een Afvoerpunt hebben

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

#PREFIX gwsw: <http://data.gwsw.nl/1.5/totaal/>
PREFIX gwsw: <{{&version}}>

SELECT ?Afvoernetwerk ?Afvoerpunt ?Afvoerrelatie ?Gebied ?uri ?type ?Buitengrens 

WHERE
{ 
    # Primaire filter wordt: deel van afvoernetwerk-uri (20220511)

    #BIND (<http://sparql.gwsw.nl/id/040654#afvoernetwerk_rwzi_denbosch> AS ?an_uri)
    BIND (<{{&an_uri}}> AS ?an_uri) .
    
#   {
#      ?conn rdf:type gwsw:BeginpuntAfvoerrelatie ;
#         gwsw:hasConnection ?punt .
#   }
#   UNION
#   {
#      ?conn rdf:type gwsw:EindpuntAfvoerrelatie ;
#        gwsw:hasConnection ?punt .
#   }
#    SERVICE <{{&endpoint}}> # endpoint van gekoppelde dataset 
#	 {

   #{ Geen UNION: alleen de relatie punt-gebied doet mee

   ?geb    gwsw:hasPart ?punt . # gebied is het subject: zoek of het een relevant afvoerpunt bevat (20220513)
   ?punt   rdf:type gwsw:Afvoerpunt ;
           gwsw:isPartOf ?an_uri ;
           rdfs:label ?Afvoerpunt .
   #}
   #UNION
   #{
   # ?rel    gwsw:isPartOf ?an_uri ;
   #         rdf:type gwsw:Afvoerrelatie ;
   #         gwsw:isPartOf ?geb ;
   #         rdfs:label ?Afvoerrelatie .
   #}

   FILTER (!(isBlank(?geb)))

   ?geb sesame:directType ?type .
   FILTER (!(isBlank(?type)))

   OPTIONAL { # Naam is niet verplicht, kan in andere dataset staan (20220518)
      ?an_uri rdfs:label ?Afvoernetwerk .
   }
   ?geb gwsw:hasAspect [
      rdf:type gwsw:Gebiedsorientatie ; # Alles met gebiedsoriëntatie en buitengrens doet mee (20200515)
      gwsw:hasAspect [
      rdf:type gwsw:Buitengrens ;
      gwsw:hasValue ?Buitengrens ; ] ] ;
      rdfs:label ?Gebied .

   # { ?geb rdf:type gwsw:Rioleringsgebied . }
   # UNION 
   # { ?geb rdf:type gwsw:Zuiveringsgebied . }
   #}
   # ?type rdfs:label ?typeNaam . # De URI hoeft niet dekkend te zijn
   # FILTER (lang(?typeNaam) = "nl") # let op! (niet meer nodig in GWSW 2.0 - prefLabel)
#   optional { ?punt gwsw:isPartOf 
#	[ 
#      rdf:type gwsw:Afvoernetwerk ;
#      rdfs:label ?Afvoernetwerk ;
#	] . }
   #BIND (strafter(str(?geb), "#") AS ?uri)

   BIND (?geb AS ?uri) # Toon de URI met de gekoppelde afvoerder
}